[package]
name = "kaneru"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya = "0.12"
clap = { version = "4.1", features = ["derive"] }
anyhow = "1"
libc = "0.2"
log = "0.4"
xdpilone = "1.0.4"
netdev = "0.30.0"
rand = "0.8.5"

[[bin]]
name = "kaneru"
path = "src/main.rs"
